DROP DATABASE IF EXISTS luxaways;
CREATE DATABASE luxaways;
use luxaways;
CREATE USER 'estef'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO 'estef'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

	<!-- generator="WordPress/6.6.2" created="2024-10-01 09:22" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>LuxAways</title>
	<link>http://localhost</link>
	<description></description>
	<pubDate>Tue, 01 Oct 2024 09:22:28 +0000</pubDate>
	<language>es</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://localhost</wp:base_site_url>
	<wp:base_blog_url>http://localhost</wp:base_blog_url>

		<wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[estef]]></wp:author_login><wp:author_email><![CDATA[rocsamcastillo@gmail.com]]></wp:author_email><wp:author_display_name><![CDATA[estef]]></wp:author_display_name><wp:author_first_name><![CDATA[Estefany]]></wp:author_first_name><wp:author_last_name><![CDATA[Pacheco]]></wp:author_last_name></wp:author>

		<wp:category>
		<wp:term_id>1</wp:term_id>
		<wp:category_nicename><![CDATA[sin-categoria]]></wp:category_nicename>
		<wp:category_parent><![CDATA[]]></wp:category_parent>
		<wp:cat_name><![CDATA[Sin categoría]]></wp:cat_name>
	</wp:category>
				<wp:term>
		<wp:term_id>4</wp:term_id>
		<wp:term_taxonomy><![CDATA[wp_template_part_area]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[header]]></wp:term_slug>
		<wp:term_parent><![CDATA[]]></wp:term_parent>
		<wp:term_name><![CDATA[header]]></wp:term_name>
	</wp:term>
		<wp:term>
		<wp:term_id>1</wp:term_id>
		<wp:term_taxonomy><![CDATA[category]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[sin-categoria]]></wp:term_slug>
		<wp:term_parent><![CDATA[]]></wp:term_parent>
		<wp:term_name><![CDATA[Sin categoría]]></wp:term_name>
	</wp:term>
		<wp:term>
		<wp:term_id>2</wp:term_id>
		<wp:term_taxonomy><![CDATA[wp_theme]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[twentytwentyfour]]></wp:term_slug>
		<wp:term_parent><![CDATA[]]></wp:term_parent>
		<wp:term_name><![CDATA[twentytwentyfour]]></wp:term_name>
	</wp:term>
		<wp:term>
		<wp:term_id>3</wp:term_id>
		<wp:term_taxonomy><![CDATA[wp_theme]]></wp:term_taxonomy>
		<wp:term_slug><![CDATA[twentytwentytwo]]></wp:term_slug>
		<wp:term_parent><![CDATA[]]></wp:term_parent>
		<wp:term_name><![CDATA[twentytwentytwo]]></wp:term_name>
	</wp:term>
		
	<generator>https://wordpress.org/?v=6.6.2</generator>

		<item>
		<title><![CDATA[¡Hola, mundo!]]></title>
		<link>http://localhost/2024/09/30/hola-mundo/</link>
		<pubDate>Mon, 30 Sep 2024 07:14:44 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/?p=1</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Te damos la bienvenida a WordPress. Esta es tu primera entrada. Edítala o bórrala, ¡luego empieza a escribir!</p>
<!-- /wp:paragraph -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>1</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 09:14:44]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 07:14:44]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 09:14:44]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 07:14:44]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[open]]></wp:ping_status>
		<wp:post_name><![CDATA[hola-mundo]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[post]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
										<category domain="category" nicename="sin-categoria"><![CDATA[Sin categoría]]></category>
						<wp:comment>
			<wp:comment_id>1</wp:comment_id>
			<wp:comment_author><![CDATA[Un comentarista de WordPress]]></wp:comment_author>
			<wp:comment_author_email><![CDATA[wapuu@wordpress.example]]></wp:comment_author_email>
			<wp:comment_author_url>https://es.wordpress.org/</wp:comment_author_url>
			<wp:comment_author_IP><![CDATA[]]></wp:comment_author_IP>
			<wp:comment_date><![CDATA[2024-09-30 09:14:44]]></wp:comment_date>
			<wp:comment_date_gmt><![CDATA[2024-09-30 07:14:44]]></wp:comment_date_gmt>
			<wp:comment_content><![CDATA[Hola, esto es un comentario.
Para empezar a moderar, editar y borrar comentarios, por favor, visita en el escritorio la pantalla de comentarios.
Los avatares de los comentaristas provienen de <a href="https://es.gravatar.com/">Gravatar</a>.]]></wp:comment_content>
			<wp:comment_approved><![CDATA[1]]></wp:comment_approved>
			<wp:comment_type><![CDATA[comment]]></wp:comment_type>
			<wp:comment_parent>0</wp:comment_parent>
			<wp:comment_user_id>0</wp:comment_user_id>
							</wp:comment>
					</item>
					<item>
		<title><![CDATA[Página de ejemplo]]></title>
		<link>http://localhost/pagina-ejemplo/</link>
		<pubDate>Mon, 30 Sep 2024 07:14:44 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/?page_id=2</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:paragraph -->
<p>Esta es una página de ejemplo. Es diferente a una entrada del blog porque permanecerá en un solo lugar y aparecerá en la navegación de tu sitio (en la mayoría de los temas). La mayoría de las personas comienzan con una página «Acerca de» que les presenta a los visitantes potenciales del sitio. Podrías decir algo así:</p>
<!-- /wp:paragraph -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>¡Hola! Soy camarero de día, aspirante a actor de noche y esta es mi web. Vivo en Mairena del Alcor, tengo un perro que se llama Firulais y me gusta el rebujito. (Y las tardes largas con café).</p></blockquote>
<!-- /wp:quote -->

<!-- wp:paragraph -->
<p>…o algo así:</p>
<!-- /wp:paragraph -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>La empresa «Mariscos Recio» fue fundada por Antonio Recio Mata. Empezó siendo una pequeña empresa que suministraba marisco a hoteles y restaurantes, pero poco a poco se ha ido transformando en un gran imperio. Mariscos Recio, el mar al mejor precio.</p></blockquote>
<!-- /wp:quote -->

<!-- wp:paragraph -->
<p>Como nuevo usuario de WordPress, deberías ir a <a href="http://localhost/wp-admin/">tu escritorio</a> para borrar esta página y crear nuevas páginas para tu contenido. ¡Pásalo bien!</p>
<!-- /wp:paragraph -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>2</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 09:14:44]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 07:14:44]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 09:14:44]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 07:14:44]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[open]]></wp:ping_status>
		<wp:post_name><![CDATA[pagina-ejemplo]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[page]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
		<wp:meta_value><![CDATA[default]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[Política de privacidad]]></title>
		<link>http://localhost/?page_id=3</link>
		<pubDate>Mon, 30 Sep 2024 07:14:44 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/?page_id=3</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:heading -->
<h2 class="wp-block-heading">Quiénes somos</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>La dirección de nuestra web es: http://localhost.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Comentarios</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Cuando los visitantes dejan comentarios en la web, recopilamos los datos que se muestran en el formulario de comentarios, así como la dirección IP del visitante y la cadena de agentes de usuario del navegador para ayudar a la detección de spam.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Una cadena anónima creada a partir de tu dirección de correo electrónico (también llamada hash) puede ser proporcionada al servicio de Gravatar para ver si la estás usando. La política de privacidad del servicio Gravatar está disponible aquí: https://automattic.com/privacy/. Después de la aprobación de tu comentario, la imagen de tu perfil es visible para el público en el contexto de tu comentario.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Medios</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Si subes imágenes a la web, deberías evitar subir imágenes con datos de ubicación (GPS EXIF) incluidos. Los visitantes de la web pueden descargar y extraer cualquier dato de ubicación de las imágenes de la web.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Cookies</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Si dejas un comentario en nuestro sitio puedes elegir guardar tu nombre, dirección de correo electrónico y web en cookies. Esto es para tu comodidad, para que no tengas que volver a rellenar tus datos cuando dejes otro comentario. Estas cookies tendrán una duración de un año.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Si tienes una cuenta y te conectas a este sitio, instalaremos una cookie temporal para determinar si tu navegador acepta cookies. Esta cookie no contiene datos personales y se elimina al cerrar el navegador.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Cuando accedas, también instalaremos varias cookies para guardar tu información de acceso y tus opciones de visualización de pantalla. Las cookies de acceso duran dos días, y las cookies de opciones de pantalla duran un año. Si seleccionas «Recuérdarme», tu acceso perdurará durante dos semanas. Si sales de tu cuenta, las cookies de acceso se eliminarán.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Si editas o publicas un artículo se guardará una cookie adicional en tu navegador. Esta cookie no incluye datos personales y simplemente indica el ID del artículo que acabas de editar. Caduca después de 1 día.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Contenido incrustado de otros sitios web</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Los artículos de este sitio pueden incluir contenido incrustado (por ejemplo, vídeos, imágenes, artículos, etc.). El contenido incrustado de otras webs se comporta exactamente de la misma manera que si el visitante hubiera visitado la otra web.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>Estas web pueden recopilar datos sobre ti, utilizar cookies, incrustar un seguimiento adicional de terceros, y supervisar tu interacción con ese contenido incrustado, incluido el seguimiento de tu interacción con el contenido incrustado si tienes una cuenta y estás conectado a esa web.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Con quién compartimos tus datos</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Si solicitas un restablecimiento de contraseña, tu dirección IP será incluida en el correo electrónico de restablecimiento.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Cuánto tiempo conservamos tus datos</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Si dejas un comentario, el comentario y sus metadatos se conservan indefinidamente. Esto es para que podamos reconocer y aprobar comentarios sucesivos automáticamente, en lugar de mantenerlos en una cola de moderación.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph -->
<p>De los usuarios que se registran en nuestra web (si los hay), también almacenamos la información personal que proporcionan en su perfil de usuario. Todos los usuarios pueden ver, editar o eliminar su información personal en cualquier momento (excepto que no pueden cambiar su nombre de usuario). Los administradores de la web también pueden ver y editar esa información.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Qué derechos tienes sobre tus datos</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Si tienes una cuenta o has dejado comentarios en esta web, puedes solicitar recibir un archivo de exportación de los datos personales que tenemos sobre ti, incluyendo cualquier dato que nos hayas proporcionado. También puedes solicitar que eliminemos cualquier dato personal que tengamos sobre ti. Esto no incluye ningún dato que estemos obligados a conservar con fines administrativos, legales o de seguridad.</p>
<!-- /wp:paragraph -->
<!-- wp:heading -->
<h2 class="wp-block-heading">Dónde se envían tus datos</h2>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p><strong class="privacy-policy-tutorial">Texto sugerido: </strong>Los comentarios de los visitantes puede que los revise un servicio de detección automática de spam.</p>
<!-- /wp:paragraph -->
]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>3</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 09:14:44]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 07:14:44]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 09:14:44]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 07:14:44]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[open]]></wp:ping_status>
		<wp:post_name><![CDATA[politica-privacidad]]></wp:post_name>
		<wp:status><![CDATA[draft]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[page]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
		<wp:meta_value><![CDATA[default]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[Navegación]]></title>
		<link>http://localhost/2024/09/30/navigation/</link>
		<pubDate>Mon, 30 Sep 2024 07:14:46 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/navigation/</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:page-list /-->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>4</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 09:14:46]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 07:14:46]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 09:14:46]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 07:14:46]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[navigation]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_navigation]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														</item>
					<item>
		<title><![CDATA[Custom Styles]]></title>
		<link>http://localhost/2024/09/30/wp-global-styles-twentytwentyfour/</link>
		<pubDate>Mon, 30 Sep 2024 07:15:44 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/wp-global-styles-twentytwentyfour/</guid>
		<description></description>
		<content:encoded><![CDATA[{"version": 3, "isGlobalStylesUserThemeJSON": true }]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>7</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 09:15:44]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 07:15:44]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 09:15:44]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 07:15:44]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[wp-global-styles-twentytwentyfour]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_global_styles]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
										<category domain="wp_theme" nicename="twentytwentyfour"><![CDATA[twentytwentyfour]]></category>
						</item>
					<item>
		<title><![CDATA[Custom Styles]]></title>
		<link>http://localhost/2024/09/30/wp-global-styles-twentytwentytwo/</link>
		<pubDate>Mon, 30 Sep 2024 17:43:33 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/wp-global-styles-twentytwentytwo/</guid>
		<description></description>
		<content:encoded><![CDATA[{"styles":{"typography":{"fontSize":"var(--wp--preset--font-size--large)","fontFamily":"var(--wp--preset--font-family--system-font)","textTransform":"capitalize"},"elements":{"heading":{"typography":{"fontFamily":"var(--wp--preset--font-family--roboto)","fontStyle":"normal","fontWeight":"200"},"color":{"text":"var:preset|color|background"}},"h1":{"typography":{"fontFamily":"var(--wp--preset--font-family--roboto)","fontSize":"var(--wp--preset--font-size--x-large)","textTransform":"uppercase"}},"link":{"typography":{"textDecoration":"none","fontFamily":"var:preset|font-family|radley","fontSize":"var(--wp--preset--font-size--medium)","fontStyle":"normal","fontWeight":"400","lineHeight":"1.3"},"color":{"text":"var(--wp--preset--color--background)"},":hover":{"color":{"text":"#1c1292"}}},"button":{"color":{"text":"var(--wp--preset--color--foreground)"}},"caption":{"color":{"text":"var(--wp--preset--color--foreground)"}}},"color":{"background":"var:preset|color|background","text":"var:preset|color|vivid-cyan-blue"}},"settings":{"typography":{"fontFamilies":{"theme":[{"fontFamily":"-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif","name":"Fuente del sistema","slug":"system-font"},{"fontFamily":"\"Source Serif Pro\", serif","name":"Source Serif Pro","slug":"source-serif-pro","fontFace":[{"fontFamily":"Source Serif Pro","fontWeight":"200 900","fontStyle":"normal","fontStretch":"normal","src":["file:.\/assets\/fonts\/source-serif-pro\/SourceSerif4Variable-Roman.ttf.woff2"]},{"fontFamily":"Source Serif Pro","fontWeight":"200 900","fontStyle":"italic","fontStretch":"normal","src":["file:.\/assets\/fonts\/source-serif-pro\/SourceSerif4Variable-Italic.ttf.woff2"]}]}],"custom":[{"name":"Roboto","slug":"roboto","fontFamily":"Roboto","fontFace":[{"fontFamily":"Roboto","fontStyle":"normal","fontWeight":"700","src":"http:\/\/localhost\/wp-content\/uploads\/fonts\/Roboto-Bold.ttf"}]},{"name":"Radley","slug":"radley","fontFamily":"Radley","preview":"","fontFace":[{"fontFamily":"Radley","fontStyle":"italic","fontWeight":"400","src":"http:\/\/localhost\/wp-content\/uploads\/fonts\/Radley-Italic.ttf"}]}]}},"color":{"palette":{"custom":[{"color":"#ffffff","name":"Color 1","slug":"custom-color-1"}]}}},"isGlobalStylesUserThemeJSON":true,"version":3}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>8</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 19:43:33]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 17:43:33]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 21:23:46]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 19:23:46]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[wp-global-styles-twentytwentytwo]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_global_styles]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
										<category domain="wp_theme" nicename="twentytwentytwo"><![CDATA[twentytwentytwo]]></category>
						</item>
					<item>
		<title><![CDATA[1]]></title>
		<link>http://localhost/1/</link>
		<pubDate>Mon, 30 Sep 2024 17:53:35 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/wp-content/uploads/2024/09/1.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>9</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 19:53:35]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 17:53:35]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 19:53:35]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 17:53:35]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[1]]></wp:post_name>
		<wp:status><![CDATA[inherit]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[attachment]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
						<wp:attachment_url><![CDATA[http://localhost/wp-content/uploads/2024/09/1.jpg]]></wp:attachment_url>
											<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>
		<wp:meta_value><![CDATA[2024/09/1.jpg]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>
		<wp:meta_value><![CDATA[a:6:{s:5:"width";i:3072;s:6:"height";i:2046;s:4:"file";s:13:"2024/09/1.jpg";s:8:"filesize";i:815760;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[Roboto]]></title>
		<link>http://localhost/2024/09/30/roboto/</link>
		<pubDate>Mon, 30 Sep 2024 17:56:53 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/roboto/</guid>
		<description></description>
		<content:encoded><![CDATA[{"fontFamily":"Roboto"}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>10</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 19:56:53]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 17:56:53]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 19:56:53]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 17:56:53]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[roboto]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_font_family]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														</item>
					<item>
		<title><![CDATA[roboto;normal;700;100%;U+0-10FFFF]]></title>
		<link>http://localhost/2024/09/30/robotonormal700100u0-10ffff/</link>
		<pubDate>Mon, 30 Sep 2024 17:56:53 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/robotonormal700100u0-10ffff/</guid>
		<description></description>
		<content:encoded><![CDATA[{"fontFamily":"Roboto","fontStyle":"normal","fontWeight":"700","src":"http:\/\/localhost\/wp-content\/uploads\/fonts\/Roboto-Bold.ttf"}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>11</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 19:56:53]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 17:56:53]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 19:56:53]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 17:56:53]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[robotonormal700100u0-10ffff]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>10</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_font_face]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_font_face_file]]></wp:meta_key>
		<wp:meta_value><![CDATA[Roboto-Bold.ttf]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[Cabecera (oscura, pequeña)]]></title>
		<link>http://localhost/2024/09/30/header-small-dark/</link>
		<pubDate>Mon, 30 Sep 2024 18:07:53 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/header-small-dark/</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:group {"metadata":{"categories":["header"],"patternName":"twentytwentytwo/header-image-background","name":"Cabecera con imagen de fondo"},"align":"full","layout":{"inherit":true,"type":"constrained"}} -->
<div class="wp-block-group alignfull"><!-- wp:cover {"url":"http://localhost/wp-content/uploads/2024/09/5-1.png","id":32,"dimRatio":0,"customOverlayColor":"#9fd0e2","isUserOverlayColor":true,"minHeight":830,"minHeightUnit":"px","contentPosition":"top left","isDark":false,"align":"full","style":{"spacing":{"padding":{"top":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dspacing\u002d\u002dsmall, 1.25rem)","bottom":"var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dspacing\u002d\u002dlarge, 8rem)"}},"color":{"duotone":"unset"}}} -->
<div class="wp-block-cover alignfull is-light has-custom-content-position is-position-top-left" style="padding-top:var(--wp--custom--spacing--small, 1.25rem);padding-bottom:var(--wp--custom--spacing--large, 8rem);min-height:830px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim" style="background-color:#9fd0e2"></span><img class="wp-block-cover__image-background wp-image-32" alt="" src="http://localhost/wp-content/uploads/2024/09/5-1.png" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"bottom":"0rem","top":"0px","right":"0px","left":"0px"}},"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}}},"textColor":"foreground","layout":{"type":"flex","justifyContent":"space-between"}} -->
<div class="wp-block-group alignwide has-foreground-color has-text-color has-link-color" style="padding-top:0px;padding-right:0px;padding-bottom:0rem;padding-left:0px"><!-- wp:site-title {"style":{"typography":{"fontStyle":"normal","fontWeight":"700"}}} /--></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group -->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>13</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 20:07:53]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 18:07:53]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 21:23:46]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 19:23:46]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[header-small-dark]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_template_part]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
										<category domain="wp_template_part_area" nicename="header"><![CDATA[header]]></category>
		<category domain="wp_theme" nicename="twentytwentytwo"><![CDATA[twentytwentytwo]]></category>
						<wp:postmeta>
		<wp:meta_key><![CDATA[origin]]></wp:meta_key>
		<wp:meta_value><![CDATA[theme]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[Inicio del blog]]></title>
		<link>http://localhost/2024/09/30/home/</link>
		<pubDate>Mon, 30 Sep 2024 18:07:54 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/home/</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:template-part {"slug":"header-small-dark","theme":"twentytwentytwo","tagName":"header"} /-->

<!-- wp:query {"queryId":0,"query":{"perPage":10,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":true},"tagName":"main","layout":{"contentSize":null,"type":"constrained"}} -->
<main class="wp-block-query"><!-- wp:post-template {"align":"wide","layout":{"type":"default"}} -->
<!-- wp:group {"layout":{"inherit":true,"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:post-featured-image {"isLink":true,"align":"wide","style":{"spacing":{"margin":{"top":"calc(1.75 * var(\u002d\u002dwp\u002d\u002dstyle\u002d\u002dblock-gap))"}}}} /-->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"650px"} -->
<div class="wp-block-column" style="flex-basis:650px"><!-- wp:post-excerpt /-->

<!-- wp:post-date {"format":"F j, Y","isLink":true,"style":{"typography":{"fontStyle":"italic","fontWeight":"400"}},"fontSize":"small"} /--></div>
<!-- /wp:column -->

<!-- wp:column {"width":""} -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":"112px"} -->
<div style="height:112px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:query-pagination {"paginationArrow":"arrow","align":"wide","layout":{"type":"flex","justifyContent":"space-between"}} -->
<!-- wp:query-pagination-previous {"fontSize":"small"} /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next {"fontSize":"small"} /-->
<!-- /wp:query-pagination --></main>
<!-- /wp:query -->

<!-- wp:template-part {"slug":"footer","theme":"twentytwentytwo","tagName":"footer"} /-->]]></content:encoded>
		<excerpt:encoded><![CDATA[Muestra las entradas más recientes, así como la página de inicio del sitio o una página personalizada definida en los ajustes de lectura. Si existe, la plantilla de página de inicio sobreescribirá a esta plantilla cuando se muestren las entradas en dicha página de inicio.]]></excerpt:encoded>
		<wp:post_id>15</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 20:07:54]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 18:07:54]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 20:07:56]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 18:07:56]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[home]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_template]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
										<category domain="wp_theme" nicename="twentytwentytwo"><![CDATA[twentytwentytwo]]></category>
						<wp:postmeta>
		<wp:meta_key><![CDATA[origin]]></wp:meta_key>
		<wp:meta_value><![CDATA[theme]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[1]]></title>
		<link>http://localhost/1-2/</link>
		<pubDate>Mon, 30 Sep 2024 18:13:33 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/wp-content/uploads/2024/09/1-1.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>18</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 20:13:33]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 18:13:33]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 20:13:33]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 18:13:33]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[1-2]]></wp:post_name>
		<wp:status><![CDATA[inherit]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[attachment]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
						<wp:attachment_url><![CDATA[http://localhost/wp-content/uploads/2024/09/1-1.jpg]]></wp:attachment_url>
											<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>
		<wp:meta_value><![CDATA[2024/09/1-1.jpg]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>
		<wp:meta_value><![CDATA[a:6:{s:5:"width";i:3072;s:6:"height";i:2046;s:4:"file";s:15:"2024/09/1-1.jpg";s:8:"filesize";i:815760;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[Navegación de Cabecera]]></title>
		<link>http://localhost/2024/09/30/navegacion-de-cabecera/</link>
		<pubDate>Mon, 30 Sep 2024 19:16:50 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/?p=21</guid>
		<description></description>
		<content:encoded><![CDATA[<!-- wp:navigation-link {"label":"Página de ejemplo","type":"page","id":2,"url":"http://localhost/pagina-ejemplo/","kind":"post-type"} /-->]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>21</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 21:16:50]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 19:16:50]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 21:16:50]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 19:16:50]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[navegacion-de-cabecera]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_navigation]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														</item>
					<item>
		<title><![CDATA[denys-nevozhai-guNIjIuUcgY-unsplash]]></title>
		<link>http://localhost/?attachment_id=22</link>
		<pubDate>Mon, 30 Sep 2024 18:28:20 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/wp-content/uploads/2024/09/denys-nevozhai-guNIjIuUcgY-unsplash.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>22</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 20:28:20]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 18:28:20]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 20:28:20]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 18:28:20]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[denys-nevozhai-gunijiuucgy-unsplash]]></wp:post_name>
		<wp:status><![CDATA[inherit]]></wp:status>
		<wp:post_parent>15</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[attachment]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
						<wp:attachment_url><![CDATA[http://localhost/wp-content/uploads/2024/09/denys-nevozhai-guNIjIuUcgY-unsplash.jpg]]></wp:attachment_url>
											<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>
		<wp:meta_value><![CDATA[2024/09/denys-nevozhai-guNIjIuUcgY-unsplash.jpg]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>
		<wp:meta_value><![CDATA[a:6:{s:5:"width";i:2992;s:6:"height";i:3992;s:4:"file";s:47:"2024/09/denys-nevozhai-guNIjIuUcgY-unsplash.jpg";s:8:"filesize";i:3775875;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[5]]></title>
		<link>http://localhost/?attachment_id=23</link>
		<pubDate>Mon, 30 Sep 2024 19:00:56 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/wp-content/uploads/2024/09/5.png</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>23</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 21:00:56]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 19:00:56]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 21:00:56]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 19:00:56]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[5]]></wp:post_name>
		<wp:status><![CDATA[inherit]]></wp:status>
		<wp:post_parent>15</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[attachment]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
						<wp:attachment_url><![CDATA[http://localhost/wp-content/uploads/2024/09/5.png]]></wp:attachment_url>
											<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>
		<wp:meta_value><![CDATA[2024/09/5.png]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>
		<wp:meta_value><![CDATA[a:6:{s:5:"width";i:1920;s:6:"height";i:1080;s:4:"file";s:13:"2024/09/5.png";s:8:"filesize";i:4000182;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[Radley]]></title>
		<link>http://localhost/2024/09/30/radley/</link>
		<pubDate>Mon, 30 Sep 2024 19:11:34 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/radley/</guid>
		<description></description>
		<content:encoded><![CDATA[{"fontFamily":"Radley"}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>24</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 21:11:34]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 19:11:34]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 21:11:34]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 19:11:34]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[radley]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_font_family]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														</item>
					<item>
		<title><![CDATA[radley;italic;400;100%;U+0-10FFFF]]></title>
		<link>http://localhost/2024/09/30/radleyitalic400100u0-10ffff/</link>
		<pubDate>Mon, 30 Sep 2024 19:11:35 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/2024/09/30/radleyitalic400100u0-10ffff/</guid>
		<description></description>
		<content:encoded><![CDATA[{"fontFamily":"Radley","fontStyle":"italic","fontWeight":"400","src":"http:\/\/localhost\/wp-content\/uploads\/fonts\/Radley-Italic.ttf"}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>25</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 21:11:35]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 19:11:35]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 21:11:35]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 19:11:35]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[radleyitalic400100u0-10ffff]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>24</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[wp_font_face]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
														<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_font_face_file]]></wp:meta_key>
		<wp:meta_value><![CDATA[Radley-Italic.ttf]]></wp:meta_value>
		</wp:postmeta>
							</item>
					<item>
		<title><![CDATA[5]]></title>
		<link>http://localhost/?attachment_id=32</link>
		<pubDate>Mon, 30 Sep 2024 19:18:10 +0000</pubDate>
		<dc:creator><![CDATA[estef]]></dc:creator>
		<guid isPermaLink="false">http://localhost/wp-content/uploads/2024/09/5-1.png</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>32</wp:post_id>
		<wp:post_date><![CDATA[2024-09-30 21:18:10]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2024-09-30 19:18:10]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[2024-09-30 21:18:10]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[2024-09-30 19:18:10]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[5-2]]></wp:post_name>
		<wp:status><![CDATA[inherit]]></wp:status>
		<wp:post_parent>15</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[attachment]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
						<wp:attachment_url><![CDATA[http://localhost/wp-content/uploads/2024/09/5-1.png]]></wp:attachment_url>
											<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>
		<wp:meta_value><![CDATA[2024/09/5-1.png]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>
		<wp:meta_value><![CDATA[a:6:{s:5:"width";i:1920;s:6:"height";i:948;s:4:"file";s:15:"2024/09/5-1.png";s:8:"filesize";i:3767793;s:5:"sizes";a:0:{}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"0";s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";s:1:"0";s:9:"copyright";s:0:"";s:12:"focal_length";s:1:"0";s:3:"iso";s:1:"0";s:13:"shutter_speed";s:1:"0";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}]]></wp:meta_value>
		</wp:postmeta>
							</item>
				</channel>
</rss>
	